data:
    image: stefanorg/data
    volumes:
        - config/httpd:/etc/services-config/httpd
        - /var/services-data/data-container/var/lib/mysql:/var/lib/mysql

workspace:
    image: stefanorg/data
    volumes:
        - magento2:/var/www/app

mysql:
  image: mysql:latest
  expose:
    - "3306"
  ports:
    - "3307:3306"
  volumes_from:
    - data
  environment:
    MYSQL_DATABASE: magento2
    MYSQL_USER: magento2
    MYSQL_PASSWORD: magento2pwd
    MYSQL_ROOT_PASSWORD: 123
web:
    build: .
    ports:
        - "80:80"
    links:
        - mysql:mysql
    volumes_from:
        - workspace
    environment:
        BASE_URL: http://magento2.dev.local
        APACHE_SERVER_NAME: magento2.dev.local
        APACHE_SERVER_ALIAS: magento2.dev.local
        DATE_TIMEZONE: Europe/Rome
